spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123
      # >=6.x com.mysql.jdbc.Driver
      # <=5.x com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
#        指定namespace
#        namespace: 6930ecc7-e326-46e8-98ae-38150d2906f9
#        cluster-name: NJ
  application:
    # 服务名称尽量用-,不要用_,不用特是字符
    name: user-center

server:
  port: 8084

